package com.hospital.register.bean;

import java.io.Serializable;
import java.util.Date;

public class BonusDetail implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_bonus_detail.bonus_id
	 * @mbg.generated
	 */
	private Integer bonusId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_bonus_detail.subscription_id
	 * @mbg.generated
	 */
	private Integer subscriptionId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_bonus_detail.settle_amount
	 * @mbg.generated
	 */
	private Long settleAmount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_bonus_detail.settle_mode
	 * @mbg.generated
	 */
	private Integer settleMode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_bonus_detail.bonus_points
	 * @mbg.generated
	 */
	private Integer bonusPoints;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_bonus_detail.complete_time
	 * @mbg.generated
	 */
	private Date completeTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_bonus_detail
	 * @mbg.generated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_bonus_detail
	 * @mbg.generated
	 */
	public BonusDetail(Integer bonusId, Integer subscriptionId, Long settleAmount, Integer settleMode,
			Integer bonusPoints, Date completeTime) {
		this.bonusId = bonusId;
		this.subscriptionId = subscriptionId;
		this.settleAmount = settleAmount;
		this.settleMode = settleMode;
		this.bonusPoints = bonusPoints;
		this.completeTime = completeTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_bonus_detail
	 * @mbg.generated
	 */
	public BonusDetail() {
		super();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bonus_detail.bonus_id
	 * @return  the value of t_bonus_detail.bonus_id
	 * @mbg.generated
	 */
	public Integer getBonusId() {
		return bonusId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bonus_detail.bonus_id
	 * @param bonusId  the value for t_bonus_detail.bonus_id
	 * @mbg.generated
	 */
	public void setBonusId(Integer bonusId) {
		this.bonusId = bonusId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bonus_detail.subscription_id
	 * @return  the value of t_bonus_detail.subscription_id
	 * @mbg.generated
	 */
	public Integer getSubscriptionId() {
		return subscriptionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bonus_detail.subscription_id
	 * @param subscriptionId  the value for t_bonus_detail.subscription_id
	 * @mbg.generated
	 */
	public void setSubscriptionId(Integer subscriptionId) {
		this.subscriptionId = subscriptionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bonus_detail.settle_amount
	 * @return  the value of t_bonus_detail.settle_amount
	 * @mbg.generated
	 */
	public Long getSettleAmount() {
		return settleAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bonus_detail.settle_amount
	 * @param settleAmount  the value for t_bonus_detail.settle_amount
	 * @mbg.generated
	 */
	public void setSettleAmount(Long settleAmount) {
		this.settleAmount = settleAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bonus_detail.settle_mode
	 * @return  the value of t_bonus_detail.settle_mode
	 * @mbg.generated
	 */
	public Integer getSettleMode() {
		return settleMode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bonus_detail.settle_mode
	 * @param settleMode  the value for t_bonus_detail.settle_mode
	 * @mbg.generated
	 */
	public void setSettleMode(Integer settleMode) {
		this.settleMode = settleMode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bonus_detail.bonus_points
	 * @return  the value of t_bonus_detail.bonus_points
	 * @mbg.generated
	 */
	public Integer getBonusPoints() {
		return bonusPoints;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bonus_detail.bonus_points
	 * @param bonusPoints  the value for t_bonus_detail.bonus_points
	 * @mbg.generated
	 */
	public void setBonusPoints(Integer bonusPoints) {
		this.bonusPoints = bonusPoints;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bonus_detail.complete_time
	 * @return  the value of t_bonus_detail.complete_time
	 * @mbg.generated
	 */
	public Date getCompleteTime() {
		return completeTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bonus_detail.complete_time
	 * @param completeTime  the value for t_bonus_detail.complete_time
	 * @mbg.generated
	 */
	public void setCompleteTime(Date completeTime) {
		this.completeTime = completeTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_bonus_detail
	 * @mbg.generated
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		BonusDetail other = (BonusDetail) that;
		return (this.getBonusId() == null ? other.getBonusId() == null : this.getBonusId().equals(other.getBonusId()))
				&& (this.getSubscriptionId() == null ? other.getSubscriptionId() == null
						: this.getSubscriptionId().equals(other.getSubscriptionId()))
				&& (this.getSettleAmount() == null ? other.getSettleAmount() == null
						: this.getSettleAmount().equals(other.getSettleAmount()))
				&& (this.getSettleMode() == null ? other.getSettleMode() == null
						: this.getSettleMode().equals(other.getSettleMode()))
				&& (this.getBonusPoints() == null ? other.getBonusPoints() == null
						: this.getBonusPoints().equals(other.getBonusPoints()))
				&& (this.getCompleteTime() == null ? other.getCompleteTime() == null
						: this.getCompleteTime().equals(other.getCompleteTime()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_bonus_detail
	 * @mbg.generated
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getBonusId() == null) ? 0 : getBonusId().hashCode());
		result = prime * result + ((getSubscriptionId() == null) ? 0 : getSubscriptionId().hashCode());
		result = prime * result + ((getSettleAmount() == null) ? 0 : getSettleAmount().hashCode());
		result = prime * result + ((getSettleMode() == null) ? 0 : getSettleMode().hashCode());
		result = prime * result + ((getBonusPoints() == null) ? 0 : getBonusPoints().hashCode());
		result = prime * result + ((getCompleteTime() == null) ? 0 : getCompleteTime().hashCode());
		return result;
	}
}