package com.hospital.register.bean;

import java.io.Serializable;
import java.util.Date;

public class Bonus implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_bonus.bonus_id
	 * @mbg.generated
	 */
	private Integer bonusId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_bonus.user_id
	 * @mbg.generated
	 */
	private Integer userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_bonus.bonus_points
	 * @mbg.generated
	 */
	private Integer bonusPoints;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_bonus.create_time
	 * @mbg.generated
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_bonus.update_time
	 * @mbg.generated
	 */
	private Date updateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_bonus
	 * @mbg.generated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_bonus
	 * @mbg.generated
	 */
	public Bonus(Integer bonusId, Integer userId, Integer bonusPoints, Date createTime, Date updateTime) {
		this.bonusId = bonusId;
		this.userId = userId;
		this.bonusPoints = bonusPoints;
		this.createTime = createTime;
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_bonus
	 * @mbg.generated
	 */
	public Bonus() {
		super();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bonus.bonus_id
	 * @return  the value of t_bonus.bonus_id
	 * @mbg.generated
	 */
	public Integer getBonusId() {
		return bonusId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bonus.bonus_id
	 * @param bonusId  the value for t_bonus.bonus_id
	 * @mbg.generated
	 */
	public void setBonusId(Integer bonusId) {
		this.bonusId = bonusId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bonus.user_id
	 * @return  the value of t_bonus.user_id
	 * @mbg.generated
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bonus.user_id
	 * @param userId  the value for t_bonus.user_id
	 * @mbg.generated
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bonus.bonus_points
	 * @return  the value of t_bonus.bonus_points
	 * @mbg.generated
	 */
	public Integer getBonusPoints() {
		return bonusPoints;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bonus.bonus_points
	 * @param bonusPoints  the value for t_bonus.bonus_points
	 * @mbg.generated
	 */
	public void setBonusPoints(Integer bonusPoints) {
		this.bonusPoints = bonusPoints;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bonus.create_time
	 * @return  the value of t_bonus.create_time
	 * @mbg.generated
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bonus.create_time
	 * @param createTime  the value for t_bonus.create_time
	 * @mbg.generated
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bonus.update_time
	 * @return  the value of t_bonus.update_time
	 * @mbg.generated
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bonus.update_time
	 * @param updateTime  the value for t_bonus.update_time
	 * @mbg.generated
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_bonus
	 * @mbg.generated
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		Bonus other = (Bonus) that;
		return (this.getBonusId() == null ? other.getBonusId() == null : this.getBonusId().equals(other.getBonusId()))
				&& (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
				&& (this.getBonusPoints() == null ? other.getBonusPoints() == null
						: this.getBonusPoints().equals(other.getBonusPoints()))
				&& (this.getCreateTime() == null ? other.getCreateTime() == null
						: this.getCreateTime().equals(other.getCreateTime()))
				&& (this.getUpdateTime() == null ? other.getUpdateTime() == null
						: this.getUpdateTime().equals(other.getUpdateTime()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_bonus
	 * @mbg.generated
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getBonusId() == null) ? 0 : getBonusId().hashCode());
		result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
		result = prime * result + ((getBonusPoints() == null) ? 0 : getBonusPoints().hashCode());
		result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
		result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
		return result;
	}
}