package com.hospital.register.bean;

import java.io.Serializable;
import java.util.Date;

public class Department implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_department.department_id
     *
     * @mbg.generated
     */
    private Integer departmentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_department.department_name
     *
     * @mbg.generated
     */
    private String departmentName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_department.department_code
     *
     * @mbg.generated
     */
    private String departmentCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_department.department_specialty
     *
     * @mbg.generated
     */
    private String departmentSpecialty;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_department.department_summary
     *
     * @mbg.generated
     */
    private String departmentSummary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_department.department_address
     *
     * @mbg.generated
     */
    private String departmentAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_department.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_department.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_department
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_department
     *
     * @mbg.generated
     */
    public Department(Integer departmentId, String departmentName, String departmentCode, String departmentSpecialty, String departmentSummary, String departmentAddress, Date createTime, Date updateTime) {
        this.departmentId = departmentId;
        this.departmentName = departmentName;
        this.departmentCode = departmentCode;
        this.departmentSpecialty = departmentSpecialty;
        this.departmentSummary = departmentSummary;
        this.departmentAddress = departmentAddress;
        this.createTime = createTime;
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_department
     *
     * @mbg.generated
     */
    public Department() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_department.department_id
     *
     * @return the value of t_department.department_id
     *
     * @mbg.generated
     */
    public Integer getDepartmentId() {
        return departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_department.department_id
     *
     * @param departmentId the value for t_department.department_id
     *
     * @mbg.generated
     */
    public void setDepartmentId(Integer departmentId) {
        this.departmentId = departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_department.department_name
     *
     * @return the value of t_department.department_name
     *
     * @mbg.generated
     */
    public String getDepartmentName() {
        return departmentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_department.department_name
     *
     * @param departmentName the value for t_department.department_name
     *
     * @mbg.generated
     */
    public void setDepartmentName(String departmentName) {
        this.departmentName = departmentName == null ? null : departmentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_department.department_code
     *
     * @return the value of t_department.department_code
     *
     * @mbg.generated
     */
    public String getDepartmentCode() {
        return departmentCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_department.department_code
     *
     * @param departmentCode the value for t_department.department_code
     *
     * @mbg.generated
     */
    public void setDepartmentCode(String departmentCode) {
        this.departmentCode = departmentCode == null ? null : departmentCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_department.department_specialty
     *
     * @return the value of t_department.department_specialty
     *
     * @mbg.generated
     */
    public String getDepartmentSpecialty() {
        return departmentSpecialty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_department.department_specialty
     *
     * @param departmentSpecialty the value for t_department.department_specialty
     *
     * @mbg.generated
     */
    public void setDepartmentSpecialty(String departmentSpecialty) {
        this.departmentSpecialty = departmentSpecialty == null ? null : departmentSpecialty.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_department.department_summary
     *
     * @return the value of t_department.department_summary
     *
     * @mbg.generated
     */
    public String getDepartmentSummary() {
        return departmentSummary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_department.department_summary
     *
     * @param departmentSummary the value for t_department.department_summary
     *
     * @mbg.generated
     */
    public void setDepartmentSummary(String departmentSummary) {
        this.departmentSummary = departmentSummary == null ? null : departmentSummary.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_department.department_address
     *
     * @return the value of t_department.department_address
     *
     * @mbg.generated
     */
    public String getDepartmentAddress() {
        return departmentAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_department.department_address
     *
     * @param departmentAddress the value for t_department.department_address
     *
     * @mbg.generated
     */
    public void setDepartmentAddress(String departmentAddress) {
        this.departmentAddress = departmentAddress == null ? null : departmentAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_department.create_time
     *
     * @return the value of t_department.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_department.create_time
     *
     * @param createTime the value for t_department.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_department.update_time
     *
     * @return the value of t_department.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_department.update_time
     *
     * @param updateTime the value for t_department.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_department
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Department other = (Department) that;
        return (this.getDepartmentId() == null ? other.getDepartmentId() == null : this.getDepartmentId().equals(other.getDepartmentId()))
            && (this.getDepartmentName() == null ? other.getDepartmentName() == null : this.getDepartmentName().equals(other.getDepartmentName()))
            && (this.getDepartmentCode() == null ? other.getDepartmentCode() == null : this.getDepartmentCode().equals(other.getDepartmentCode()))
            && (this.getDepartmentSpecialty() == null ? other.getDepartmentSpecialty() == null : this.getDepartmentSpecialty().equals(other.getDepartmentSpecialty()))
            && (this.getDepartmentSummary() == null ? other.getDepartmentSummary() == null : this.getDepartmentSummary().equals(other.getDepartmentSummary()))
            && (this.getDepartmentAddress() == null ? other.getDepartmentAddress() == null : this.getDepartmentAddress().equals(other.getDepartmentAddress()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_department
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getDepartmentId() == null) ? 0 : getDepartmentId().hashCode());
        result = prime * result + ((getDepartmentName() == null) ? 0 : getDepartmentName().hashCode());
        result = prime * result + ((getDepartmentCode() == null) ? 0 : getDepartmentCode().hashCode());
        result = prime * result + ((getDepartmentSpecialty() == null) ? 0 : getDepartmentSpecialty().hashCode());
        result = prime * result + ((getDepartmentSummary() == null) ? 0 : getDepartmentSummary().hashCode());
        result = prime * result + ((getDepartmentAddress() == null) ? 0 : getDepartmentAddress().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        return result;
    }
}