package com.hospital.register.bean;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class ScheduleExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_schedule
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_schedule
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_schedule
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_schedule
     *
     * @mbg.generated
     */
    public ScheduleExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_schedule
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_schedule
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_schedule
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_schedule
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_schedule
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_schedule
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_schedule
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_schedule
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_schedule
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_schedule
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_schedule
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        protected void addCriterionForJDBCTime(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Time(value.getTime()), property);
        }

        protected void addCriterionForJDBCTime(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Time> timeList = new ArrayList<java.sql.Time>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                timeList.add(new java.sql.Time(iter.next().getTime()));
            }
            addCriterion(condition, timeList, property);
        }

        protected void addCriterionForJDBCTime(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Time(value1.getTime()), new java.sql.Time(value2.getTime()), property);
        }

        public Criteria andScheduleIdIsNull() {
            addCriterion("schedule_id is null");
            return (Criteria) this;
        }

        public Criteria andScheduleIdIsNotNull() {
            addCriterion("schedule_id is not null");
            return (Criteria) this;
        }

        public Criteria andScheduleIdEqualTo(Integer value) {
            addCriterion("schedule_id =", value, "scheduleId");
            return (Criteria) this;
        }

        public Criteria andScheduleIdNotEqualTo(Integer value) {
            addCriterion("schedule_id <>", value, "scheduleId");
            return (Criteria) this;
        }

        public Criteria andScheduleIdGreaterThan(Integer value) {
            addCriterion("schedule_id >", value, "scheduleId");
            return (Criteria) this;
        }

        public Criteria andScheduleIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("schedule_id >=", value, "scheduleId");
            return (Criteria) this;
        }

        public Criteria andScheduleIdLessThan(Integer value) {
            addCriterion("schedule_id <", value, "scheduleId");
            return (Criteria) this;
        }

        public Criteria andScheduleIdLessThanOrEqualTo(Integer value) {
            addCriterion("schedule_id <=", value, "scheduleId");
            return (Criteria) this;
        }

        public Criteria andScheduleIdIn(List<Integer> values) {
            addCriterion("schedule_id in", values, "scheduleId");
            return (Criteria) this;
        }

        public Criteria andScheduleIdNotIn(List<Integer> values) {
            addCriterion("schedule_id not in", values, "scheduleId");
            return (Criteria) this;
        }

        public Criteria andScheduleIdBetween(Integer value1, Integer value2) {
            addCriterion("schedule_id between", value1, value2, "scheduleId");
            return (Criteria) this;
        }

        public Criteria andScheduleIdNotBetween(Integer value1, Integer value2) {
            addCriterion("schedule_id not between", value1, value2, "scheduleId");
            return (Criteria) this;
        }

        public Criteria andHospitalIdIsNull() {
            addCriterion("hospital_id is null");
            return (Criteria) this;
        }

        public Criteria andHospitalIdIsNotNull() {
            addCriterion("hospital_id is not null");
            return (Criteria) this;
        }

        public Criteria andHospitalIdEqualTo(Integer value) {
            addCriterion("hospital_id =", value, "hospitalId");
            return (Criteria) this;
        }

        public Criteria andHospitalIdNotEqualTo(Integer value) {
            addCriterion("hospital_id <>", value, "hospitalId");
            return (Criteria) this;
        }

        public Criteria andHospitalIdGreaterThan(Integer value) {
            addCriterion("hospital_id >", value, "hospitalId");
            return (Criteria) this;
        }

        public Criteria andHospitalIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("hospital_id >=", value, "hospitalId");
            return (Criteria) this;
        }

        public Criteria andHospitalIdLessThan(Integer value) {
            addCriterion("hospital_id <", value, "hospitalId");
            return (Criteria) this;
        }

        public Criteria andHospitalIdLessThanOrEqualTo(Integer value) {
            addCriterion("hospital_id <=", value, "hospitalId");
            return (Criteria) this;
        }

        public Criteria andHospitalIdIn(List<Integer> values) {
            addCriterion("hospital_id in", values, "hospitalId");
            return (Criteria) this;
        }

        public Criteria andHospitalIdNotIn(List<Integer> values) {
            addCriterion("hospital_id not in", values, "hospitalId");
            return (Criteria) this;
        }

        public Criteria andHospitalIdBetween(Integer value1, Integer value2) {
            addCriterion("hospital_id between", value1, value2, "hospitalId");
            return (Criteria) this;
        }

        public Criteria andHospitalIdNotBetween(Integer value1, Integer value2) {
            addCriterion("hospital_id not between", value1, value2, "hospitalId");
            return (Criteria) this;
        }

        public Criteria andDoctorIdIsNull() {
            addCriterion("doctor_id is null");
            return (Criteria) this;
        }

        public Criteria andDoctorIdIsNotNull() {
            addCriterion("doctor_id is not null");
            return (Criteria) this;
        }

        public Criteria andDoctorIdEqualTo(Integer value) {
            addCriterion("doctor_id =", value, "doctorId");
            return (Criteria) this;
        }

        public Criteria andDoctorIdNotEqualTo(Integer value) {
            addCriterion("doctor_id <>", value, "doctorId");
            return (Criteria) this;
        }

        public Criteria andDoctorIdGreaterThan(Integer value) {
            addCriterion("doctor_id >", value, "doctorId");
            return (Criteria) this;
        }

        public Criteria andDoctorIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("doctor_id >=", value, "doctorId");
            return (Criteria) this;
        }

        public Criteria andDoctorIdLessThan(Integer value) {
            addCriterion("doctor_id <", value, "doctorId");
            return (Criteria) this;
        }

        public Criteria andDoctorIdLessThanOrEqualTo(Integer value) {
            addCriterion("doctor_id <=", value, "doctorId");
            return (Criteria) this;
        }

        public Criteria andDoctorIdIn(List<Integer> values) {
            addCriterion("doctor_id in", values, "doctorId");
            return (Criteria) this;
        }

        public Criteria andDoctorIdNotIn(List<Integer> values) {
            addCriterion("doctor_id not in", values, "doctorId");
            return (Criteria) this;
        }

        public Criteria andDoctorIdBetween(Integer value1, Integer value2) {
            addCriterion("doctor_id between", value1, value2, "doctorId");
            return (Criteria) this;
        }

        public Criteria andDoctorIdNotBetween(Integer value1, Integer value2) {
            addCriterion("doctor_id not between", value1, value2, "doctorId");
            return (Criteria) this;
        }

        public Criteria andDepartmentIdIsNull() {
            addCriterion("department_id is null");
            return (Criteria) this;
        }

        public Criteria andDepartmentIdIsNotNull() {
            addCriterion("department_id is not null");
            return (Criteria) this;
        }

        public Criteria andDepartmentIdEqualTo(Integer value) {
            addCriterion("department_id =", value, "departmentId");
            return (Criteria) this;
        }

        public Criteria andDepartmentIdNotEqualTo(Integer value) {
            addCriterion("department_id <>", value, "departmentId");
            return (Criteria) this;
        }

        public Criteria andDepartmentIdGreaterThan(Integer value) {
            addCriterion("department_id >", value, "departmentId");
            return (Criteria) this;
        }

        public Criteria andDepartmentIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("department_id >=", value, "departmentId");
            return (Criteria) this;
        }

        public Criteria andDepartmentIdLessThan(Integer value) {
            addCriterion("department_id <", value, "departmentId");
            return (Criteria) this;
        }

        public Criteria andDepartmentIdLessThanOrEqualTo(Integer value) {
            addCriterion("department_id <=", value, "departmentId");
            return (Criteria) this;
        }

        public Criteria andDepartmentIdIn(List<Integer> values) {
            addCriterion("department_id in", values, "departmentId");
            return (Criteria) this;
        }

        public Criteria andDepartmentIdNotIn(List<Integer> values) {
            addCriterion("department_id not in", values, "departmentId");
            return (Criteria) this;
        }

        public Criteria andDepartmentIdBetween(Integer value1, Integer value2) {
            addCriterion("department_id between", value1, value2, "departmentId");
            return (Criteria) this;
        }

        public Criteria andDepartmentIdNotBetween(Integer value1, Integer value2) {
            addCriterion("department_id not between", value1, value2, "departmentId");
            return (Criteria) this;
        }

        public Criteria andClinicDateIsNull() {
            addCriterion("clinic_date is null");
            return (Criteria) this;
        }

        public Criteria andClinicDateIsNotNull() {
            addCriterion("clinic_date is not null");
            return (Criteria) this;
        }

        public Criteria andClinicDateEqualTo(Date value) {
            addCriterionForJDBCDate("clinic_date =", value, "clinicDate");
            return (Criteria) this;
        }

        public Criteria andClinicDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("clinic_date <>", value, "clinicDate");
            return (Criteria) this;
        }

        public Criteria andClinicDateGreaterThan(Date value) {
            addCriterionForJDBCDate("clinic_date >", value, "clinicDate");
            return (Criteria) this;
        }

        public Criteria andClinicDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("clinic_date >=", value, "clinicDate");
            return (Criteria) this;
        }

        public Criteria andClinicDateLessThan(Date value) {
            addCriterionForJDBCDate("clinic_date <", value, "clinicDate");
            return (Criteria) this;
        }

        public Criteria andClinicDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("clinic_date <=", value, "clinicDate");
            return (Criteria) this;
        }

        public Criteria andClinicDateIn(List<Date> values) {
            addCriterionForJDBCDate("clinic_date in", values, "clinicDate");
            return (Criteria) this;
        }

        public Criteria andClinicDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("clinic_date not in", values, "clinicDate");
            return (Criteria) this;
        }

        public Criteria andClinicDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("clinic_date between", value1, value2, "clinicDate");
            return (Criteria) this;
        }

        public Criteria andClinicDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("clinic_date not between", value1, value2, "clinicDate");
            return (Criteria) this;
        }

        public Criteria andClinicTimeIsNull() {
            addCriterion("clinic_time is null");
            return (Criteria) this;
        }

        public Criteria andClinicTimeIsNotNull() {
            addCriterion("clinic_time is not null");
            return (Criteria) this;
        }

        public Criteria andClinicTimeEqualTo(Date value) {
            addCriterionForJDBCTime("clinic_time =", value, "clinicTime");
            return (Criteria) this;
        }

        public Criteria andClinicTimeNotEqualTo(Date value) {
            addCriterionForJDBCTime("clinic_time <>", value, "clinicTime");
            return (Criteria) this;
        }

        public Criteria andClinicTimeGreaterThan(Date value) {
            addCriterionForJDBCTime("clinic_time >", value, "clinicTime");
            return (Criteria) this;
        }

        public Criteria andClinicTimeGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCTime("clinic_time >=", value, "clinicTime");
            return (Criteria) this;
        }

        public Criteria andClinicTimeLessThan(Date value) {
            addCriterionForJDBCTime("clinic_time <", value, "clinicTime");
            return (Criteria) this;
        }

        public Criteria andClinicTimeLessThanOrEqualTo(Date value) {
            addCriterionForJDBCTime("clinic_time <=", value, "clinicTime");
            return (Criteria) this;
        }

        public Criteria andClinicTimeIn(List<Date> values) {
            addCriterionForJDBCTime("clinic_time in", values, "clinicTime");
            return (Criteria) this;
        }

        public Criteria andClinicTimeNotIn(List<Date> values) {
            addCriterionForJDBCTime("clinic_time not in", values, "clinicTime");
            return (Criteria) this;
        }

        public Criteria andClinicTimeBetween(Date value1, Date value2) {
            addCriterionForJDBCTime("clinic_time between", value1, value2, "clinicTime");
            return (Criteria) this;
        }

        public Criteria andClinicTimeNotBetween(Date value1, Date value2) {
            addCriterionForJDBCTime("clinic_time not between", value1, value2, "clinicTime");
            return (Criteria) this;
        }

        public Criteria andClinicWeekIsNull() {
            addCriterion("clinic_week is null");
            return (Criteria) this;
        }

        public Criteria andClinicWeekIsNotNull() {
            addCriterion("clinic_week is not null");
            return (Criteria) this;
        }

        public Criteria andClinicWeekEqualTo(Integer value) {
            addCriterion("clinic_week =", value, "clinicWeek");
            return (Criteria) this;
        }

        public Criteria andClinicWeekNotEqualTo(Integer value) {
            addCriterion("clinic_week <>", value, "clinicWeek");
            return (Criteria) this;
        }

        public Criteria andClinicWeekGreaterThan(Integer value) {
            addCriterion("clinic_week >", value, "clinicWeek");
            return (Criteria) this;
        }

        public Criteria andClinicWeekGreaterThanOrEqualTo(Integer value) {
            addCriterion("clinic_week >=", value, "clinicWeek");
            return (Criteria) this;
        }

        public Criteria andClinicWeekLessThan(Integer value) {
            addCriterion("clinic_week <", value, "clinicWeek");
            return (Criteria) this;
        }

        public Criteria andClinicWeekLessThanOrEqualTo(Integer value) {
            addCriterion("clinic_week <=", value, "clinicWeek");
            return (Criteria) this;
        }

        public Criteria andClinicWeekIn(List<Integer> values) {
            addCriterion("clinic_week in", values, "clinicWeek");
            return (Criteria) this;
        }

        public Criteria andClinicWeekNotIn(List<Integer> values) {
            addCriterion("clinic_week not in", values, "clinicWeek");
            return (Criteria) this;
        }

        public Criteria andClinicWeekBetween(Integer value1, Integer value2) {
            addCriterion("clinic_week between", value1, value2, "clinicWeek");
            return (Criteria) this;
        }

        public Criteria andClinicWeekNotBetween(Integer value1, Integer value2) {
            addCriterion("clinic_week not between", value1, value2, "clinicWeek");
            return (Criteria) this;
        }

        public Criteria andClinicTypeIsNull() {
            addCriterion("clinic_type is null");
            return (Criteria) this;
        }

        public Criteria andClinicTypeIsNotNull() {
            addCriterion("clinic_type is not null");
            return (Criteria) this;
        }

        public Criteria andClinicTypeEqualTo(Integer value) {
            addCriterion("clinic_type =", value, "clinicType");
            return (Criteria) this;
        }

        public Criteria andClinicTypeNotEqualTo(Integer value) {
            addCriterion("clinic_type <>", value, "clinicType");
            return (Criteria) this;
        }

        public Criteria andClinicTypeGreaterThan(Integer value) {
            addCriterion("clinic_type >", value, "clinicType");
            return (Criteria) this;
        }

        public Criteria andClinicTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("clinic_type >=", value, "clinicType");
            return (Criteria) this;
        }

        public Criteria andClinicTypeLessThan(Integer value) {
            addCriterion("clinic_type <", value, "clinicType");
            return (Criteria) this;
        }

        public Criteria andClinicTypeLessThanOrEqualTo(Integer value) {
            addCriterion("clinic_type <=", value, "clinicType");
            return (Criteria) this;
        }

        public Criteria andClinicTypeIn(List<Integer> values) {
            addCriterion("clinic_type in", values, "clinicType");
            return (Criteria) this;
        }

        public Criteria andClinicTypeNotIn(List<Integer> values) {
            addCriterion("clinic_type not in", values, "clinicType");
            return (Criteria) this;
        }

        public Criteria andClinicTypeBetween(Integer value1, Integer value2) {
            addCriterion("clinic_type between", value1, value2, "clinicType");
            return (Criteria) this;
        }

        public Criteria andClinicTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("clinic_type not between", value1, value2, "clinicType");
            return (Criteria) this;
        }

        public Criteria andClinicStatusIsNull() {
            addCriterion("clinic_status is null");
            return (Criteria) this;
        }

        public Criteria andClinicStatusIsNotNull() {
            addCriterion("clinic_status is not null");
            return (Criteria) this;
        }

        public Criteria andClinicStatusEqualTo(Integer value) {
            addCriterion("clinic_status =", value, "clinicStatus");
            return (Criteria) this;
        }

        public Criteria andClinicStatusNotEqualTo(Integer value) {
            addCriterion("clinic_status <>", value, "clinicStatus");
            return (Criteria) this;
        }

        public Criteria andClinicStatusGreaterThan(Integer value) {
            addCriterion("clinic_status >", value, "clinicStatus");
            return (Criteria) this;
        }

        public Criteria andClinicStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("clinic_status >=", value, "clinicStatus");
            return (Criteria) this;
        }

        public Criteria andClinicStatusLessThan(Integer value) {
            addCriterion("clinic_status <", value, "clinicStatus");
            return (Criteria) this;
        }

        public Criteria andClinicStatusLessThanOrEqualTo(Integer value) {
            addCriterion("clinic_status <=", value, "clinicStatus");
            return (Criteria) this;
        }

        public Criteria andClinicStatusIn(List<Integer> values) {
            addCriterion("clinic_status in", values, "clinicStatus");
            return (Criteria) this;
        }

        public Criteria andClinicStatusNotIn(List<Integer> values) {
            addCriterion("clinic_status not in", values, "clinicStatus");
            return (Criteria) this;
        }

        public Criteria andClinicStatusBetween(Integer value1, Integer value2) {
            addCriterion("clinic_status between", value1, value2, "clinicStatus");
            return (Criteria) this;
        }

        public Criteria andClinicStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("clinic_status not between", value1, value2, "clinicStatus");
            return (Criteria) this;
        }

        public Criteria andClinicNoIsNull() {
            addCriterion("clinic_no is null");
            return (Criteria) this;
        }

        public Criteria andClinicNoIsNotNull() {
            addCriterion("clinic_no is not null");
            return (Criteria) this;
        }

        public Criteria andClinicNoEqualTo(Integer value) {
            addCriterion("clinic_no =", value, "clinicNo");
            return (Criteria) this;
        }

        public Criteria andClinicNoNotEqualTo(Integer value) {
            addCriterion("clinic_no <>", value, "clinicNo");
            return (Criteria) this;
        }

        public Criteria andClinicNoGreaterThan(Integer value) {
            addCriterion("clinic_no >", value, "clinicNo");
            return (Criteria) this;
        }

        public Criteria andClinicNoGreaterThanOrEqualTo(Integer value) {
            addCriterion("clinic_no >=", value, "clinicNo");
            return (Criteria) this;
        }

        public Criteria andClinicNoLessThan(Integer value) {
            addCriterion("clinic_no <", value, "clinicNo");
            return (Criteria) this;
        }

        public Criteria andClinicNoLessThanOrEqualTo(Integer value) {
            addCriterion("clinic_no <=", value, "clinicNo");
            return (Criteria) this;
        }

        public Criteria andClinicNoIn(List<Integer> values) {
            addCriterion("clinic_no in", values, "clinicNo");
            return (Criteria) this;
        }

        public Criteria andClinicNoNotIn(List<Integer> values) {
            addCriterion("clinic_no not in", values, "clinicNo");
            return (Criteria) this;
        }

        public Criteria andClinicNoBetween(Integer value1, Integer value2) {
            addCriterion("clinic_no between", value1, value2, "clinicNo");
            return (Criteria) this;
        }

        public Criteria andClinicNoNotBetween(Integer value1, Integer value2) {
            addCriterion("clinic_no not between", value1, value2, "clinicNo");
            return (Criteria) this;
        }

        public Criteria andClinicFeeIsNull() {
            addCriterion("clinic_fee is null");
            return (Criteria) this;
        }

        public Criteria andClinicFeeIsNotNull() {
            addCriterion("clinic_fee is not null");
            return (Criteria) this;
        }

        public Criteria andClinicFeeEqualTo(BigDecimal value) {
            addCriterion("clinic_fee =", value, "clinicFee");
            return (Criteria) this;
        }

        public Criteria andClinicFeeNotEqualTo(BigDecimal value) {
            addCriterion("clinic_fee <>", value, "clinicFee");
            return (Criteria) this;
        }

        public Criteria andClinicFeeGreaterThan(BigDecimal value) {
            addCriterion("clinic_fee >", value, "clinicFee");
            return (Criteria) this;
        }

        public Criteria andClinicFeeGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("clinic_fee >=", value, "clinicFee");
            return (Criteria) this;
        }

        public Criteria andClinicFeeLessThan(BigDecimal value) {
            addCriterion("clinic_fee <", value, "clinicFee");
            return (Criteria) this;
        }

        public Criteria andClinicFeeLessThanOrEqualTo(BigDecimal value) {
            addCriterion("clinic_fee <=", value, "clinicFee");
            return (Criteria) this;
        }

        public Criteria andClinicFeeIn(List<BigDecimal> values) {
            addCriterion("clinic_fee in", values, "clinicFee");
            return (Criteria) this;
        }

        public Criteria andClinicFeeNotIn(List<BigDecimal> values) {
            addCriterion("clinic_fee not in", values, "clinicFee");
            return (Criteria) this;
        }

        public Criteria andClinicFeeBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("clinic_fee between", value1, value2, "clinicFee");
            return (Criteria) this;
        }

        public Criteria andClinicFeeNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("clinic_fee not between", value1, value2, "clinicFee");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_schedule
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_schedule
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}