package com.hospital.register.dao;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.hospital.register.bean.Bonus;
import com.hospital.register.bean.BonusExample;
import com.hospital.register.vo.UserBonusVO;

public interface BonusMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bonus
     *
     * @mbg.generated
     */
    long countByExample(BonusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bonus
     *
     * @mbg.generated
     */
    int deleteByExample(BonusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bonus
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer bonusId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bonus
     *
     * @mbg.generated
     */
    int insert(Bonus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bonus
     *
     * @mbg.generated
     */
    int insertSelective(Bonus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bonus
     *
     * @mbg.generated
     */
    List<Bonus> selectByExample(BonusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bonus
     *
     * @mbg.generated
     */
    Bonus selectByPrimaryKey(Integer bonusId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bonus
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Bonus record, @Param("example") BonusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bonus
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Bonus record, @Param("example") BonusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bonus
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Bonus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bonus
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Bonus record);
    
    /**
     * 
     * @param paramsMap
     * @return
     */
    long countByCondition(Map<String,Object> paramsMap);
    
    /**
     * 
     * @param paramsMap
     * @return
     */
    List<UserBonusVO> selectBonusByCondition(Map<String,Object> paramsMap);
}